#!/usr/bin/env ruby
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'yaml'
require 'active_record'
configs = YAML.load(File.read("config/database.yml.example"))
ActiveRecord::Base.establish_connection(configs['development'])

require 'translated_collection'

def conn
  ActiveRecord::Base.connection
end

def upperfn
  lambda {|elt| elt.upcase }
end

def lowerfn
  lambda {|elt| elt.downcase }
end

def collection
  %w[a b c d e f g h i j k l]
end

def wrapone
  TranslatedCollection::Wrapper.new(collection, lowerfn, upperfn)
end

def wrapped
  @wrapped ||= wrapone
end

begin
  require 'pry'
  Pry.start
rescue LoadError
  require 'irb'
  IRB.start
end

